//! GENERATED by gen.py from the resolved WIT: do not edit.
//! A wasm32 pass-through of the selected WASI interfaces.
#![allow(unused, clippy::all, non_camel_case_types)]
wit_bindgen::generate!({ path: "wit", world: "proxy", generate_all });
pub struct Component;

impl crate::exports::wasi::cli::environment::Guest for Component {
    fn get_environment() -> Vec<(String, String)> {
        let r = crate::wasi::cli::environment::get_environment();
        r
    }
    fn get_arguments() -> Vec<String> {
        let r = crate::wasi::cli::environment::get_arguments();
        r
    }
    fn initial_cwd() -> Option<String> {
        let r = crate::wasi::cli::environment::initial_cwd();
        r
    }
}

impl crate::exports::wasi::cli::exit::Guest for Component {
    fn exit(status: Result<(), ()>) {
        crate::wasi::cli::exit::exit(status);
    }
    fn exit_with_code(status_code: u8) {
        crate::wasi::cli::exit::exit_with_code(status_code);
    }
}

pub struct PxError(pub crate::wasi::io::error::Error);
impl crate::exports::wasi::io::error::Guest for Component {
    type Error = PxError;
}
impl crate::exports::wasi::io::error::GuestError for PxError {
    fn to_debug_string(&self) -> String {
        let r = self.0.to_debug_string();
        r
    }
}

pub struct PxPollable(pub crate::wasi::io::poll::Pollable);
impl crate::exports::wasi::io::poll::Guest for Component {
    type Pollable = PxPollable;
    fn poll(in_: Vec<crate::exports::wasi::io::poll::PollableBorrow<'_>>) -> Vec<u32> {
        let r = crate::wasi::io::poll::poll(&in_.iter().map(|v| &v.get::<PxPollable>().0).collect::<Vec<_>>());
        r
    }
}
impl crate::exports::wasi::io::poll::GuestPollable for PxPollable {
    fn ready(&self) -> bool {
        let r = self.0.ready();
        r
    }
    fn block(&self) {
        self.0.block();
    }
}

pub struct PxInputStream(pub crate::wasi::io::streams::InputStream);
pub struct PxOutputStream(pub crate::wasi::io::streams::OutputStream);
impl crate::exports::wasi::io::streams::Guest for Component {
    type InputStream = PxInputStream;
    type OutputStream = PxOutputStream;
}
impl crate::exports::wasi::io::streams::GuestInputStream for PxInputStream {
    fn read(&self, len: u64) -> Result<Vec<u8>, crate::exports::wasi::io::streams::StreamError> {
        let r = self.0.read(len);
        match r { Ok(v) => Ok(v), Err(e) => Err(conv_i2e_stream_error_9(e)) }
    }
    fn blocking_read(&self, len: u64) -> Result<Vec<u8>, crate::exports::wasi::io::streams::StreamError> {
        let r = self.0.blocking_read(len);
        match r { Ok(v) => Ok(v), Err(e) => Err(conv_i2e_stream_error_9(e)) }
    }
    fn skip(&self, len: u64) -> Result<u64, crate::exports::wasi::io::streams::StreamError> {
        let r = self.0.skip(len);
        match r { Ok(v) => Ok(v), Err(e) => Err(conv_i2e_stream_error_9(e)) }
    }
    fn blocking_skip(&self, len: u64) -> Result<u64, crate::exports::wasi::io::streams::StreamError> {
        let r = self.0.blocking_skip(len);
        match r { Ok(v) => Ok(v), Err(e) => Err(conv_i2e_stream_error_9(e)) }
    }
    fn subscribe(&self) -> crate::exports::wasi::io::poll::Pollable {
        let r = self.0.subscribe();
        crate::exports::wasi::io::poll::Pollable::new(PxPollable(r))
    }
}
impl crate::exports::wasi::io::streams::GuestOutputStream for PxOutputStream {
    fn check_write(&self) -> Result<u64, crate::exports::wasi::io::streams::StreamError> {
        let r = self.0.check_write();
        match r { Ok(v) => Ok(v), Err(e) => Err(conv_i2e_stream_error_9(e)) }
    }
    fn write(&self, contents: Vec<u8>) -> Result<(), crate::exports::wasi::io::streams::StreamError> {
        let r = self.0.write(&contents);
        match r { Ok(()) => Ok(()), Err(e) => Err(conv_i2e_stream_error_9(e)) }
    }
    fn blocking_write_and_flush(&self, contents: Vec<u8>) -> Result<(), crate::exports::wasi::io::streams::StreamError> {
        let r = self.0.blocking_write_and_flush(&contents);
        match r { Ok(()) => Ok(()), Err(e) => Err(conv_i2e_stream_error_9(e)) }
    }
    fn flush(&self) -> Result<(), crate::exports::wasi::io::streams::StreamError> {
        let r = self.0.flush();
        match r { Ok(()) => Ok(()), Err(e) => Err(conv_i2e_stream_error_9(e)) }
    }
    fn blocking_flush(&self) -> Result<(), crate::exports::wasi::io::streams::StreamError> {
        let r = self.0.blocking_flush();
        match r { Ok(()) => Ok(()), Err(e) => Err(conv_i2e_stream_error_9(e)) }
    }
    fn subscribe(&self) -> crate::exports::wasi::io::poll::Pollable {
        let r = self.0.subscribe();
        crate::exports::wasi::io::poll::Pollable::new(PxPollable(r))
    }
    fn write_zeroes(&self, len: u64) -> Result<(), crate::exports::wasi::io::streams::StreamError> {
        let r = self.0.write_zeroes(len);
        match r { Ok(()) => Ok(()), Err(e) => Err(conv_i2e_stream_error_9(e)) }
    }
    fn blocking_write_zeroes_and_flush(&self, len: u64) -> Result<(), crate::exports::wasi::io::streams::StreamError> {
        let r = self.0.blocking_write_zeroes_and_flush(len);
        match r { Ok(()) => Ok(()), Err(e) => Err(conv_i2e_stream_error_9(e)) }
    }
    fn splice(&self, src: crate::exports::wasi::io::streams::InputStreamBorrow<'_>, len: u64) -> Result<u64, crate::exports::wasi::io::streams::StreamError> {
        let r = self.0.splice(&src.get::<PxInputStream>().0, len);
        match r { Ok(v) => Ok(v), Err(e) => Err(conv_i2e_stream_error_9(e)) }
    }
    fn blocking_splice(&self, src: crate::exports::wasi::io::streams::InputStreamBorrow<'_>, len: u64) -> Result<u64, crate::exports::wasi::io::streams::StreamError> {
        let r = self.0.blocking_splice(&src.get::<PxInputStream>().0, len);
        match r { Ok(v) => Ok(v), Err(e) => Err(conv_i2e_stream_error_9(e)) }
    }
}

impl crate::exports::wasi::cli::stdin::Guest for Component {
    fn get_stdin() -> crate::exports::wasi::io::streams::InputStream {
        let r = crate::wasi::cli::stdin::get_stdin();
        crate::exports::wasi::io::streams::InputStream::new(PxInputStream(r))
    }
}

impl crate::exports::wasi::cli::stdout::Guest for Component {
    fn get_stdout() -> crate::exports::wasi::io::streams::OutputStream {
        let r = crate::wasi::cli::stdout::get_stdout();
        crate::exports::wasi::io::streams::OutputStream::new(PxOutputStream(r))
    }
}

impl crate::exports::wasi::cli::stderr::Guest for Component {
    fn get_stderr() -> crate::exports::wasi::io::streams::OutputStream {
        let r = crate::wasi::cli::stderr::get_stderr();
        crate::exports::wasi::io::streams::OutputStream::new(PxOutputStream(r))
    }
}

pub struct PxTerminalInput(pub crate::wasi::cli::terminal_input::TerminalInput);
impl crate::exports::wasi::cli::terminal_input::Guest for Component {
    type TerminalInput = PxTerminalInput;
}
impl crate::exports::wasi::cli::terminal_input::GuestTerminalInput for PxTerminalInput {
}

pub struct PxTerminalOutput(pub crate::wasi::cli::terminal_output::TerminalOutput);
impl crate::exports::wasi::cli::terminal_output::Guest for Component {
    type TerminalOutput = PxTerminalOutput;
}
impl crate::exports::wasi::cli::terminal_output::GuestTerminalOutput for PxTerminalOutput {
}

impl crate::exports::wasi::cli::terminal_stdin::Guest for Component {
    fn get_terminal_stdin() -> Option<crate::exports::wasi::cli::terminal_input::TerminalInput> {
        let r = crate::wasi::cli::terminal_stdin::get_terminal_stdin();
        r.map(|v| crate::exports::wasi::cli::terminal_input::TerminalInput::new(PxTerminalInput(v)))
    }
}

impl crate::exports::wasi::cli::terminal_stdout::Guest for Component {
    fn get_terminal_stdout() -> Option<crate::exports::wasi::cli::terminal_output::TerminalOutput> {
        let r = crate::wasi::cli::terminal_stdout::get_terminal_stdout();
        r.map(|v| crate::exports::wasi::cli::terminal_output::TerminalOutput::new(PxTerminalOutput(v)))
    }
}

impl crate::exports::wasi::cli::terminal_stderr::Guest for Component {
    fn get_terminal_stderr() -> Option<crate::exports::wasi::cli::terminal_output::TerminalOutput> {
        let r = crate::wasi::cli::terminal_stderr::get_terminal_stderr();
        r.map(|v| crate::exports::wasi::cli::terminal_output::TerminalOutput::new(PxTerminalOutput(v)))
    }
}

impl crate::exports::wasi::clocks::monotonic_clock::Guest for Component {
    fn now() -> u64 {
        let r = crate::wasi::clocks::monotonic_clock::now();
        r
    }
    fn resolution() -> u64 {
        let r = crate::wasi::clocks::monotonic_clock::resolution();
        r
    }
    fn subscribe_instant(when: u64) -> crate::exports::wasi::io::poll::Pollable {
        let r = crate::wasi::clocks::monotonic_clock::subscribe_instant(when);
        crate::exports::wasi::io::poll::Pollable::new(PxPollable(r))
    }
    fn subscribe_duration(when: u64) -> crate::exports::wasi::io::poll::Pollable {
        let r = crate::wasi::clocks::monotonic_clock::subscribe_duration(when);
        crate::exports::wasi::io::poll::Pollable::new(PxPollable(r))
    }
}

impl crate::exports::wasi::clocks::wall_clock::Guest for Component {
    fn now() -> crate::exports::wasi::clocks::wall_clock::Datetime {
        let r = crate::wasi::clocks::wall_clock::now();
        conv_i2e_datetime_22(r)
    }
    fn resolution() -> crate::exports::wasi::clocks::wall_clock::Datetime {
        let r = crate::wasi::clocks::wall_clock::resolution();
        conv_i2e_datetime_22(r)
    }
}

pub struct PxDescriptor(pub crate::wasi::filesystem::types::Descriptor);
pub struct PxDirectoryEntryStream(pub crate::wasi::filesystem::types::DirectoryEntryStream);
impl crate::exports::wasi::filesystem::types::Guest for Component {
    type Descriptor = PxDescriptor;
    type DirectoryEntryStream = PxDirectoryEntryStream;
    fn filesystem_error_code(err: crate::exports::wasi::io::error::ErrorBorrow<'_>) -> Option<crate::exports::wasi::filesystem::types::ErrorCode> {
        let r = crate::wasi::filesystem::types::filesystem_error_code(&err.get::<PxError>().0);
        r.map(|v| conv_i2e_error_code_38(v))
    }
}
impl crate::exports::wasi::filesystem::types::GuestDescriptor for PxDescriptor {
    fn read_via_stream(&self, offset: u64) -> Result<crate::exports::wasi::io::streams::InputStream, crate::exports::wasi::filesystem::types::ErrorCode> {
        let r = self.0.read_via_stream(offset);
        match r { Ok(v) => Ok(crate::exports::wasi::io::streams::InputStream::new(PxInputStream(v))), Err(e) => Err(conv_i2e_error_code_38(e)) }
    }
    fn write_via_stream(&self, offset: u64) -> Result<crate::exports::wasi::io::streams::OutputStream, crate::exports::wasi::filesystem::types::ErrorCode> {
        let r = self.0.write_via_stream(offset);
        match r { Ok(v) => Ok(crate::exports::wasi::io::streams::OutputStream::new(PxOutputStream(v))), Err(e) => Err(conv_i2e_error_code_38(e)) }
    }
    fn append_via_stream(&self) -> Result<crate::exports::wasi::io::streams::OutputStream, crate::exports::wasi::filesystem::types::ErrorCode> {
        let r = self.0.append_via_stream();
        match r { Ok(v) => Ok(crate::exports::wasi::io::streams::OutputStream::new(PxOutputStream(v))), Err(e) => Err(conv_i2e_error_code_38(e)) }
    }
    fn advise(&self, offset: u64, length: u64, advice: crate::exports::wasi::filesystem::types::Advice) -> Result<(), crate::exports::wasi::filesystem::types::ErrorCode> {
        let r = self.0.advise(offset, length, conv_e2i_advice_39(advice));
        match r { Ok(()) => Ok(()), Err(e) => Err(conv_i2e_error_code_38(e)) }
    }
    fn sync_data(&self) -> Result<(), crate::exports::wasi::filesystem::types::ErrorCode> {
        let r = self.0.sync_data();
        match r { Ok(()) => Ok(()), Err(e) => Err(conv_i2e_error_code_38(e)) }
    }
    fn get_flags(&self) -> Result<crate::exports::wasi::filesystem::types::DescriptorFlags, crate::exports::wasi::filesystem::types::ErrorCode> {
        let r = self.0.get_flags();
        match r { Ok(v) => Ok(conv_i2e_descriptor_flags_30(v)), Err(e) => Err(conv_i2e_error_code_38(e)) }
    }
    fn get_type(&self) -> Result<crate::exports::wasi::filesystem::types::DescriptorType, crate::exports::wasi::filesystem::types::ErrorCode> {
        let r = self.0.get_type();
        match r { Ok(v) => Ok(conv_i2e_descriptor_type_29(v)), Err(e) => Err(conv_i2e_error_code_38(e)) }
    }
    fn set_size(&self, size: u64) -> Result<(), crate::exports::wasi::filesystem::types::ErrorCode> {
        let r = self.0.set_size(size);
        match r { Ok(()) => Ok(()), Err(e) => Err(conv_i2e_error_code_38(e)) }
    }
    fn set_times(&self, data_access_timestamp: crate::exports::wasi::filesystem::types::NewTimestamp, data_modification_timestamp: crate::exports::wasi::filesystem::types::NewTimestamp) -> Result<(), crate::exports::wasi::filesystem::types::ErrorCode> {
        let r = self.0.set_times(conv_e2i_new_timestamp_36(data_access_timestamp), conv_e2i_new_timestamp_36(data_modification_timestamp));
        match r { Ok(()) => Ok(()), Err(e) => Err(conv_i2e_error_code_38(e)) }
    }
    fn read(&self, length: u64, offset: u64) -> Result<(Vec<u8>, bool), crate::exports::wasi::filesystem::types::ErrorCode> {
        let r = self.0.read(length, offset);
        match r { Ok(v) => Ok(v), Err(e) => Err(conv_i2e_error_code_38(e)) }
    }
    fn write(&self, buffer: Vec<u8>, offset: u64) -> Result<u64, crate::exports::wasi::filesystem::types::ErrorCode> {
        let r = self.0.write(&buffer, offset);
        match r { Ok(v) => Ok(v), Err(e) => Err(conv_i2e_error_code_38(e)) }
    }
    fn read_directory(&self) -> Result<crate::exports::wasi::filesystem::types::DirectoryEntryStream, crate::exports::wasi::filesystem::types::ErrorCode> {
        let r = self.0.read_directory();
        match r { Ok(v) => Ok(crate::exports::wasi::filesystem::types::DirectoryEntryStream::new(PxDirectoryEntryStream(v))), Err(e) => Err(conv_i2e_error_code_38(e)) }
    }
    fn sync(&self) -> Result<(), crate::exports::wasi::filesystem::types::ErrorCode> {
        let r = self.0.sync();
        match r { Ok(()) => Ok(()), Err(e) => Err(conv_i2e_error_code_38(e)) }
    }
    fn create_directory_at(&self, path: String) -> Result<(), crate::exports::wasi::filesystem::types::ErrorCode> {
        let r = self.0.create_directory_at(&path);
        match r { Ok(()) => Ok(()), Err(e) => Err(conv_i2e_error_code_38(e)) }
    }
    fn stat(&self) -> Result<crate::exports::wasi::filesystem::types::DescriptorStat, crate::exports::wasi::filesystem::types::ErrorCode> {
        let r = self.0.stat();
        match r { Ok(v) => Ok(conv_i2e_descriptor_stat_35(v)), Err(e) => Err(conv_i2e_error_code_38(e)) }
    }
    fn stat_at(&self, path_flags: crate::exports::wasi::filesystem::types::PathFlags, path: String) -> Result<crate::exports::wasi::filesystem::types::DescriptorStat, crate::exports::wasi::filesystem::types::ErrorCode> {
        let r = self.0.stat_at(conv_e2i_path_flags_31(path_flags), &path);
        match r { Ok(v) => Ok(conv_i2e_descriptor_stat_35(v)), Err(e) => Err(conv_i2e_error_code_38(e)) }
    }
    fn set_times_at(&self, path_flags: crate::exports::wasi::filesystem::types::PathFlags, path: String, data_access_timestamp: crate::exports::wasi::filesystem::types::NewTimestamp, data_modification_timestamp: crate::exports::wasi::filesystem::types::NewTimestamp) -> Result<(), crate::exports::wasi::filesystem::types::ErrorCode> {
        let r = self.0.set_times_at(conv_e2i_path_flags_31(path_flags), &path, conv_e2i_new_timestamp_36(data_access_timestamp), conv_e2i_new_timestamp_36(data_modification_timestamp));
        match r { Ok(()) => Ok(()), Err(e) => Err(conv_i2e_error_code_38(e)) }
    }
    fn link_at(&self, old_path_flags: crate::exports::wasi::filesystem::types::PathFlags, old_path: String, new_descriptor: crate::exports::wasi::filesystem::types::DescriptorBorrow<'_>, new_path: String) -> Result<(), crate::exports::wasi::filesystem::types::ErrorCode> {
        let r = self.0.link_at(conv_e2i_path_flags_31(old_path_flags), &old_path, &new_descriptor.get::<PxDescriptor>().0, &new_path);
        match r { Ok(()) => Ok(()), Err(e) => Err(conv_i2e_error_code_38(e)) }
    }
    fn open_at(&self, path_flags: crate::exports::wasi::filesystem::types::PathFlags, path: String, open_flags: crate::exports::wasi::filesystem::types::OpenFlags, flags: crate::exports::wasi::filesystem::types::DescriptorFlags) -> Result<crate::exports::wasi::filesystem::types::Descriptor, crate::exports::wasi::filesystem::types::ErrorCode> {
        let r = self.0.open_at(conv_e2i_path_flags_31(path_flags), &path, conv_e2i_open_flags_32(open_flags), conv_e2i_descriptor_flags_30(flags));
        match r { Ok(v) => Ok(crate::exports::wasi::filesystem::types::Descriptor::new(PxDescriptor(v))), Err(e) => Err(conv_i2e_error_code_38(e)) }
    }
    fn readlink_at(&self, path: String) -> Result<String, crate::exports::wasi::filesystem::types::ErrorCode> {
        let r = self.0.readlink_at(&path);
        match r { Ok(v) => Ok(v), Err(e) => Err(conv_i2e_error_code_38(e)) }
    }
    fn remove_directory_at(&self, path: String) -> Result<(), crate::exports::wasi::filesystem::types::ErrorCode> {
        let r = self.0.remove_directory_at(&path);
        match r { Ok(()) => Ok(()), Err(e) => Err(conv_i2e_error_code_38(e)) }
    }
    fn rename_at(&self, old_path: String, new_descriptor: crate::exports::wasi::filesystem::types::DescriptorBorrow<'_>, new_path: String) -> Result<(), crate::exports::wasi::filesystem::types::ErrorCode> {
        let r = self.0.rename_at(&old_path, &new_descriptor.get::<PxDescriptor>().0, &new_path);
        match r { Ok(()) => Ok(()), Err(e) => Err(conv_i2e_error_code_38(e)) }
    }
    fn symlink_at(&self, old_path: String, new_path: String) -> Result<(), crate::exports::wasi::filesystem::types::ErrorCode> {
        let r = self.0.symlink_at(&old_path, &new_path);
        match r { Ok(()) => Ok(()), Err(e) => Err(conv_i2e_error_code_38(e)) }
    }
    fn unlink_file_at(&self, path: String) -> Result<(), crate::exports::wasi::filesystem::types::ErrorCode> {
        let r = self.0.unlink_file_at(&path);
        match r { Ok(()) => Ok(()), Err(e) => Err(conv_i2e_error_code_38(e)) }
    }
    fn is_same_object(&self, other: crate::exports::wasi::filesystem::types::DescriptorBorrow<'_>) -> bool {
        let r = self.0.is_same_object(&other.get::<PxDescriptor>().0);
        r
    }
    fn metadata_hash(&self) -> Result<crate::exports::wasi::filesystem::types::MetadataHashValue, crate::exports::wasi::filesystem::types::ErrorCode> {
        let r = self.0.metadata_hash();
        match r { Ok(v) => Ok(conv_i2e_metadata_hash_value_40(v)), Err(e) => Err(conv_i2e_error_code_38(e)) }
    }
    fn metadata_hash_at(&self, path_flags: crate::exports::wasi::filesystem::types::PathFlags, path: String) -> Result<crate::exports::wasi::filesystem::types::MetadataHashValue, crate::exports::wasi::filesystem::types::ErrorCode> {
        let r = self.0.metadata_hash_at(conv_e2i_path_flags_31(path_flags), &path);
        match r { Ok(v) => Ok(conv_i2e_metadata_hash_value_40(v)), Err(e) => Err(conv_i2e_error_code_38(e)) }
    }
}
impl crate::exports::wasi::filesystem::types::GuestDirectoryEntryStream for PxDirectoryEntryStream {
    fn read_directory_entry(&self) -> Result<Option<crate::exports::wasi::filesystem::types::DirectoryEntry>, crate::exports::wasi::filesystem::types::ErrorCode> {
        let r = self.0.read_directory_entry();
        match r { Ok(v) => Ok(v.map(|v| conv_i2e_directory_entry_37(v))), Err(e) => Err(conv_i2e_error_code_38(e)) }
    }
}

impl crate::exports::wasi::filesystem::preopens::Guest for Component {
    fn get_directories() -> Vec<(crate::exports::wasi::filesystem::types::Descriptor, String)> {
        let r = crate::wasi::filesystem::preopens::get_directories();
        r.into_iter().map(|v| { let (t0, t1,) = v; (crate::exports::wasi::filesystem::types::Descriptor::new(PxDescriptor(t0)), t1,) }).collect::<Vec<_>>()
    }
}

impl crate::exports::wasi::random::insecure_seed::Guest for Component {
    fn insecure_seed() -> (u64, u64) {
        let r = crate::wasi::random::insecure_seed::insecure_seed();
        r
    }
}

impl crate::exports::wasi::random::insecure::Guest for Component {
    fn get_insecure_random_bytes(len: u64) -> Vec<u8> {
        let r = crate::wasi::random::insecure::get_insecure_random_bytes(len);
        r
    }
    fn get_insecure_random_u64() -> u64 {
        let r = crate::wasi::random::insecure::get_insecure_random_u64();
        r
    }
}

impl crate::exports::wasi::random::random::Guest for Component {
    fn get_random_bytes(len: u64) -> Vec<u8> {
        let r = crate::wasi::random::random::get_random_bytes(len);
        r
    }
    fn get_random_u64() -> u64 {
        let r = crate::wasi::random::random::get_random_u64();
        r
    }
}

pub struct PxNetwork(pub crate::wasi::sockets::network::Network);
impl crate::exports::wasi::sockets::network::Guest for Component {
    type Network = PxNetwork;
}
impl crate::exports::wasi::sockets::network::GuestNetwork for PxNetwork {
}

impl crate::exports::wasi::sockets::instance_network::Guest for Component {
    fn instance_network() -> crate::exports::wasi::sockets::network::Network {
        let r = crate::wasi::sockets::instance_network::instance_network();
        crate::exports::wasi::sockets::network::Network::new(PxNetwork(r))
    }
}

pub struct PxResolveAddressStream(pub crate::wasi::sockets::ip_name_lookup::ResolveAddressStream);
impl crate::exports::wasi::sockets::ip_name_lookup::Guest for Component {
    type ResolveAddressStream = PxResolveAddressStream;
    fn resolve_addresses(network: crate::exports::wasi::sockets::network::NetworkBorrow<'_>, name: String) -> Result<crate::exports::wasi::sockets::ip_name_lookup::ResolveAddressStream, crate::exports::wasi::sockets::network::ErrorCode> {
        let r = crate::wasi::sockets::ip_name_lookup::resolve_addresses(&network.get::<PxNetwork>().0, &name);
        match r { Ok(v) => Ok(crate::exports::wasi::sockets::ip_name_lookup::ResolveAddressStream::new(PxResolveAddressStream(v))), Err(e) => Err(conv_i2e_error_code_72(e)) }
    }
}
impl crate::exports::wasi::sockets::ip_name_lookup::GuestResolveAddressStream for PxResolveAddressStream {
    fn resolve_next_address(&self) -> Result<Option<crate::exports::wasi::sockets::network::IpAddress>, crate::exports::wasi::sockets::network::ErrorCode> {
        let r = self.0.resolve_next_address();
        match r { Ok(v) => Ok(v.map(|v| conv_i2e_ip_address_76(v))), Err(e) => Err(conv_i2e_error_code_72(e)) }
    }
    fn subscribe(&self) -> crate::exports::wasi::io::poll::Pollable {
        let r = self.0.subscribe();
        crate::exports::wasi::io::poll::Pollable::new(PxPollable(r))
    }
}

pub struct PxTcpSocket(pub crate::wasi::sockets::tcp::TcpSocket);
impl crate::exports::wasi::sockets::tcp::Guest for Component {
    type TcpSocket = PxTcpSocket;
}
impl crate::exports::wasi::sockets::tcp::GuestTcpSocket for PxTcpSocket {
    fn start_bind(&self, network: crate::exports::wasi::sockets::network::NetworkBorrow<'_>, local_address: crate::exports::wasi::sockets::network::IpSocketAddress) -> Result<(), crate::exports::wasi::sockets::network::ErrorCode> {
        let r = self.0.start_bind(&network.get::<PxNetwork>().0, conv_e2i_ip_socket_address_79(local_address));
        match r { Ok(()) => Ok(()), Err(e) => Err(conv_i2e_error_code_72(e)) }
    }
    fn finish_bind(&self) -> Result<(), crate::exports::wasi::sockets::network::ErrorCode> {
        let r = self.0.finish_bind();
        match r { Ok(()) => Ok(()), Err(e) => Err(conv_i2e_error_code_72(e)) }
    }
    fn start_connect(&self, network: crate::exports::wasi::sockets::network::NetworkBorrow<'_>, remote_address: crate::exports::wasi::sockets::network::IpSocketAddress) -> Result<(), crate::exports::wasi::sockets::network::ErrorCode> {
        let r = self.0.start_connect(&network.get::<PxNetwork>().0, conv_e2i_ip_socket_address_79(remote_address));
        match r { Ok(()) => Ok(()), Err(e) => Err(conv_i2e_error_code_72(e)) }
    }
    fn finish_connect(&self) -> Result<(crate::exports::wasi::io::streams::InputStream, crate::exports::wasi::io::streams::OutputStream), crate::exports::wasi::sockets::network::ErrorCode> {
        let r = self.0.finish_connect();
        match r { Ok(v) => Ok({ let (t0, t1,) = v; (crate::exports::wasi::io::streams::InputStream::new(PxInputStream(t0)), crate::exports::wasi::io::streams::OutputStream::new(PxOutputStream(t1)),) }), Err(e) => Err(conv_i2e_error_code_72(e)) }
    }
    fn start_listen(&self) -> Result<(), crate::exports::wasi::sockets::network::ErrorCode> {
        let r = self.0.start_listen();
        match r { Ok(()) => Ok(()), Err(e) => Err(conv_i2e_error_code_72(e)) }
    }
    fn finish_listen(&self) -> Result<(), crate::exports::wasi::sockets::network::ErrorCode> {
        let r = self.0.finish_listen();
        match r { Ok(()) => Ok(()), Err(e) => Err(conv_i2e_error_code_72(e)) }
    }
    fn accept(&self) -> Result<(crate::exports::wasi::sockets::tcp::TcpSocket, crate::exports::wasi::io::streams::InputStream, crate::exports::wasi::io::streams::OutputStream), crate::exports::wasi::sockets::network::ErrorCode> {
        let r = self.0.accept();
        match r { Ok(v) => Ok({ let (t0, t1, t2,) = v; (crate::exports::wasi::sockets::tcp::TcpSocket::new(PxTcpSocket(t0)), crate::exports::wasi::io::streams::InputStream::new(PxInputStream(t1)), crate::exports::wasi::io::streams::OutputStream::new(PxOutputStream(t2)),) }), Err(e) => Err(conv_i2e_error_code_72(e)) }
    }
    fn local_address(&self) -> Result<crate::exports::wasi::sockets::network::IpSocketAddress, crate::exports::wasi::sockets::network::ErrorCode> {
        let r = self.0.local_address();
        match r { Ok(v) => Ok(conv_i2e_ip_socket_address_79(v)), Err(e) => Err(conv_i2e_error_code_72(e)) }
    }
    fn remote_address(&self) -> Result<crate::exports::wasi::sockets::network::IpSocketAddress, crate::exports::wasi::sockets::network::ErrorCode> {
        let r = self.0.remote_address();
        match r { Ok(v) => Ok(conv_i2e_ip_socket_address_79(v)), Err(e) => Err(conv_i2e_error_code_72(e)) }
    }
    fn is_listening(&self) -> bool {
        let r = self.0.is_listening();
        r
    }
    fn address_family(&self) -> crate::exports::wasi::sockets::network::IpAddressFamily {
        let r = self.0.address_family();
        conv_i2e_ip_address_family_73(r)
    }
    fn set_listen_backlog_size(&self, value: u64) -> Result<(), crate::exports::wasi::sockets::network::ErrorCode> {
        let r = self.0.set_listen_backlog_size(value);
        match r { Ok(()) => Ok(()), Err(e) => Err(conv_i2e_error_code_72(e)) }
    }
    fn keep_alive_enabled(&self) -> Result<bool, crate::exports::wasi::sockets::network::ErrorCode> {
        let r = self.0.keep_alive_enabled();
        match r { Ok(v) => Ok(v), Err(e) => Err(conv_i2e_error_code_72(e)) }
    }
    fn set_keep_alive_enabled(&self, value: bool) -> Result<(), crate::exports::wasi::sockets::network::ErrorCode> {
        let r = self.0.set_keep_alive_enabled(value);
        match r { Ok(()) => Ok(()), Err(e) => Err(conv_i2e_error_code_72(e)) }
    }
    fn keep_alive_idle_time(&self) -> Result<u64, crate::exports::wasi::sockets::network::ErrorCode> {
        let r = self.0.keep_alive_idle_time();
        match r { Ok(v) => Ok(v), Err(e) => Err(conv_i2e_error_code_72(e)) }
    }
    fn set_keep_alive_idle_time(&self, value: u64) -> Result<(), crate::exports::wasi::sockets::network::ErrorCode> {
        let r = self.0.set_keep_alive_idle_time(value);
        match r { Ok(()) => Ok(()), Err(e) => Err(conv_i2e_error_code_72(e)) }
    }
    fn keep_alive_interval(&self) -> Result<u64, crate::exports::wasi::sockets::network::ErrorCode> {
        let r = self.0.keep_alive_interval();
        match r { Ok(v) => Ok(v), Err(e) => Err(conv_i2e_error_code_72(e)) }
    }
    fn set_keep_alive_interval(&self, value: u64) -> Result<(), crate::exports::wasi::sockets::network::ErrorCode> {
        let r = self.0.set_keep_alive_interval(value);
        match r { Ok(()) => Ok(()), Err(e) => Err(conv_i2e_error_code_72(e)) }
    }
    fn keep_alive_count(&self) -> Result<u32, crate::exports::wasi::sockets::network::ErrorCode> {
        let r = self.0.keep_alive_count();
        match r { Ok(v) => Ok(v), Err(e) => Err(conv_i2e_error_code_72(e)) }
    }
    fn set_keep_alive_count(&self, value: u32) -> Result<(), crate::exports::wasi::sockets::network::ErrorCode> {
        let r = self.0.set_keep_alive_count(value);
        match r { Ok(()) => Ok(()), Err(e) => Err(conv_i2e_error_code_72(e)) }
    }
    fn hop_limit(&self) -> Result<u8, crate::exports::wasi::sockets::network::ErrorCode> {
        let r = self.0.hop_limit();
        match r { Ok(v) => Ok(v), Err(e) => Err(conv_i2e_error_code_72(e)) }
    }
    fn set_hop_limit(&self, value: u8) -> Result<(), crate::exports::wasi::sockets::network::ErrorCode> {
        let r = self.0.set_hop_limit(value);
        match r { Ok(()) => Ok(()), Err(e) => Err(conv_i2e_error_code_72(e)) }
    }
    fn receive_buffer_size(&self) -> Result<u64, crate::exports::wasi::sockets::network::ErrorCode> {
        let r = self.0.receive_buffer_size();
        match r { Ok(v) => Ok(v), Err(e) => Err(conv_i2e_error_code_72(e)) }
    }
    fn set_receive_buffer_size(&self, value: u64) -> Result<(), crate::exports::wasi::sockets::network::ErrorCode> {
        let r = self.0.set_receive_buffer_size(value);
        match r { Ok(()) => Ok(()), Err(e) => Err(conv_i2e_error_code_72(e)) }
    }
    fn send_buffer_size(&self) -> Result<u64, crate::exports::wasi::sockets::network::ErrorCode> {
        let r = self.0.send_buffer_size();
        match r { Ok(v) => Ok(v), Err(e) => Err(conv_i2e_error_code_72(e)) }
    }
    fn set_send_buffer_size(&self, value: u64) -> Result<(), crate::exports::wasi::sockets::network::ErrorCode> {
        let r = self.0.set_send_buffer_size(value);
        match r { Ok(()) => Ok(()), Err(e) => Err(conv_i2e_error_code_72(e)) }
    }
    fn subscribe(&self) -> crate::exports::wasi::io::poll::Pollable {
        let r = self.0.subscribe();
        crate::exports::wasi::io::poll::Pollable::new(PxPollable(r))
    }
    fn shutdown(&self, shutdown_type: crate::exports::wasi::sockets::tcp::ShutdownType) -> Result<(), crate::exports::wasi::sockets::network::ErrorCode> {
        let r = self.0.shutdown(conv_e2i_shutdown_type_100(shutdown_type));
        match r { Ok(()) => Ok(()), Err(e) => Err(conv_i2e_error_code_72(e)) }
    }
}

impl crate::exports::wasi::sockets::tcp_create_socket::Guest for Component {
    fn create_tcp_socket(address_family: crate::exports::wasi::sockets::network::IpAddressFamily) -> Result<crate::exports::wasi::sockets::tcp::TcpSocket, crate::exports::wasi::sockets::network::ErrorCode> {
        let r = crate::wasi::sockets::tcp_create_socket::create_tcp_socket(conv_e2i_ip_address_family_73(address_family));
        match r { Ok(v) => Ok(crate::exports::wasi::sockets::tcp::TcpSocket::new(PxTcpSocket(v))), Err(e) => Err(conv_i2e_error_code_72(e)) }
    }
}

pub struct PxUdpSocket(pub crate::wasi::sockets::udp::UdpSocket);
pub struct PxIncomingDatagramStream(pub crate::wasi::sockets::udp::IncomingDatagramStream);
pub struct PxOutgoingDatagramStream(pub crate::wasi::sockets::udp::OutgoingDatagramStream);
impl crate::exports::wasi::sockets::udp::Guest for Component {
    type UdpSocket = PxUdpSocket;
    type IncomingDatagramStream = PxIncomingDatagramStream;
    type OutgoingDatagramStream = PxOutgoingDatagramStream;
}
impl crate::exports::wasi::sockets::udp::GuestUdpSocket for PxUdpSocket {
    fn start_bind(&self, network: crate::exports::wasi::sockets::network::NetworkBorrow<'_>, local_address: crate::exports::wasi::sockets::network::IpSocketAddress) -> Result<(), crate::exports::wasi::sockets::network::ErrorCode> {
        let r = self.0.start_bind(&network.get::<PxNetwork>().0, conv_e2i_ip_socket_address_79(local_address));
        match r { Ok(()) => Ok(()), Err(e) => Err(conv_i2e_error_code_72(e)) }
    }
    fn finish_bind(&self) -> Result<(), crate::exports::wasi::sockets::network::ErrorCode> {
        let r = self.0.finish_bind();
        match r { Ok(()) => Ok(()), Err(e) => Err(conv_i2e_error_code_72(e)) }
    }
    fn stream(&self, remote_address: Option<crate::exports::wasi::sockets::network::IpSocketAddress>) -> Result<(crate::exports::wasi::sockets::udp::IncomingDatagramStream, crate::exports::wasi::sockets::udp::OutgoingDatagramStream), crate::exports::wasi::sockets::network::ErrorCode> {
        let r = self.0.stream(remote_address.map(|v| conv_e2i_ip_socket_address_79(v)));
        match r { Ok(v) => Ok({ let (t0, t1,) = v; (crate::exports::wasi::sockets::udp::IncomingDatagramStream::new(PxIncomingDatagramStream(t0)), crate::exports::wasi::sockets::udp::OutgoingDatagramStream::new(PxOutgoingDatagramStream(t1)),) }), Err(e) => Err(conv_i2e_error_code_72(e)) }
    }
    fn local_address(&self) -> Result<crate::exports::wasi::sockets::network::IpSocketAddress, crate::exports::wasi::sockets::network::ErrorCode> {
        let r = self.0.local_address();
        match r { Ok(v) => Ok(conv_i2e_ip_socket_address_79(v)), Err(e) => Err(conv_i2e_error_code_72(e)) }
    }
    fn remote_address(&self) -> Result<crate::exports::wasi::sockets::network::IpSocketAddress, crate::exports::wasi::sockets::network::ErrorCode> {
        let r = self.0.remote_address();
        match r { Ok(v) => Ok(conv_i2e_ip_socket_address_79(v)), Err(e) => Err(conv_i2e_error_code_72(e)) }
    }
    fn address_family(&self) -> crate::exports::wasi::sockets::network::IpAddressFamily {
        let r = self.0.address_family();
        conv_i2e_ip_address_family_73(r)
    }
    fn unicast_hop_limit(&self) -> Result<u8, crate::exports::wasi::sockets::network::ErrorCode> {
        let r = self.0.unicast_hop_limit();
        match r { Ok(v) => Ok(v), Err(e) => Err(conv_i2e_error_code_72(e)) }
    }
    fn set_unicast_hop_limit(&self, value: u8) -> Result<(), crate::exports::wasi::sockets::network::ErrorCode> {
        let r = self.0.set_unicast_hop_limit(value);
        match r { Ok(()) => Ok(()), Err(e) => Err(conv_i2e_error_code_72(e)) }
    }
    fn receive_buffer_size(&self) -> Result<u64, crate::exports::wasi::sockets::network::ErrorCode> {
        let r = self.0.receive_buffer_size();
        match r { Ok(v) => Ok(v), Err(e) => Err(conv_i2e_error_code_72(e)) }
    }
    fn set_receive_buffer_size(&self, value: u64) -> Result<(), crate::exports::wasi::sockets::network::ErrorCode> {
        let r = self.0.set_receive_buffer_size(value);
        match r { Ok(()) => Ok(()), Err(e) => Err(conv_i2e_error_code_72(e)) }
    }
    fn send_buffer_size(&self) -> Result<u64, crate::exports::wasi::sockets::network::ErrorCode> {
        let r = self.0.send_buffer_size();
        match r { Ok(v) => Ok(v), Err(e) => Err(conv_i2e_error_code_72(e)) }
    }
    fn set_send_buffer_size(&self, value: u64) -> Result<(), crate::exports::wasi::sockets::network::ErrorCode> {
        let r = self.0.set_send_buffer_size(value);
        match r { Ok(()) => Ok(()), Err(e) => Err(conv_i2e_error_code_72(e)) }
    }
    fn subscribe(&self) -> crate::exports::wasi::io::poll::Pollable {
        let r = self.0.subscribe();
        crate::exports::wasi::io::poll::Pollable::new(PxPollable(r))
    }
}
impl crate::exports::wasi::sockets::udp::GuestIncomingDatagramStream for PxIncomingDatagramStream {
    fn receive(&self, max_results: u64) -> Result<Vec<crate::exports::wasi::sockets::udp::IncomingDatagram>, crate::exports::wasi::sockets::network::ErrorCode> {
        let r = self.0.receive(max_results);
        match r { Ok(v) => Ok(v.into_iter().map(|v| conv_i2e_incoming_datagram_130(v)).collect::<Vec<_>>()), Err(e) => Err(conv_i2e_error_code_72(e)) }
    }
    fn subscribe(&self) -> crate::exports::wasi::io::poll::Pollable {
        let r = self.0.subscribe();
        crate::exports::wasi::io::poll::Pollable::new(PxPollable(r))
    }
}
impl crate::exports::wasi::sockets::udp::GuestOutgoingDatagramStream for PxOutgoingDatagramStream {
    fn check_send(&self) -> Result<u64, crate::exports::wasi::sockets::network::ErrorCode> {
        let r = self.0.check_send();
        match r { Ok(v) => Ok(v), Err(e) => Err(conv_i2e_error_code_72(e)) }
    }
    fn send(&self, datagrams: Vec<crate::exports::wasi::sockets::udp::OutgoingDatagram>) -> Result<u64, crate::exports::wasi::sockets::network::ErrorCode> {
        let r = self.0.send(&datagrams.into_iter().map(|v| conv_e2i_outgoing_datagram_132(v)).collect::<Vec<_>>());
        match r { Ok(v) => Ok(v), Err(e) => Err(conv_i2e_error_code_72(e)) }
    }
    fn subscribe(&self) -> crate::exports::wasi::io::poll::Pollable {
        let r = self.0.subscribe();
        crate::exports::wasi::io::poll::Pollable::new(PxPollable(r))
    }
}

impl crate::exports::wasi::sockets::udp_create_socket::Guest for Component {
    fn create_udp_socket(address_family: crate::exports::wasi::sockets::network::IpAddressFamily) -> Result<crate::exports::wasi::sockets::udp::UdpSocket, crate::exports::wasi::sockets::network::ErrorCode> {
        let r = crate::wasi::sockets::udp_create_socket::create_udp_socket(conv_e2i_ip_address_family_73(address_family));
        match r { Ok(v) => Ok(crate::exports::wasi::sockets::udp::UdpSocket::new(PxUdpSocket(v))), Err(e) => Err(conv_i2e_error_code_72(e)) }
    }
}

fn conv_e2i_descriptor_flags_30(x: crate::exports::wasi::filesystem::types::DescriptorFlags) -> crate::wasi::filesystem::types::DescriptorFlags {
    crate::wasi::filesystem::types::DescriptorFlags::from_bits_truncate(x.bits())
}
fn conv_e2i_path_flags_31(x: crate::exports::wasi::filesystem::types::PathFlags) -> crate::wasi::filesystem::types::PathFlags {
    crate::wasi::filesystem::types::PathFlags::from_bits_truncate(x.bits())
}
fn conv_e2i_open_flags_32(x: crate::exports::wasi::filesystem::types::OpenFlags) -> crate::wasi::filesystem::types::OpenFlags {
    crate::wasi::filesystem::types::OpenFlags::from_bits_truncate(x.bits())
}
fn conv_e2i_new_timestamp_36(x: crate::exports::wasi::filesystem::types::NewTimestamp) -> crate::wasi::filesystem::types::NewTimestamp {
    match x {
        crate::exports::wasi::filesystem::types::NewTimestamp::NoChange => crate::wasi::filesystem::types::NewTimestamp::NoChange,
        crate::exports::wasi::filesystem::types::NewTimestamp::Now => crate::wasi::filesystem::types::NewTimestamp::Now,
        crate::exports::wasi::filesystem::types::NewTimestamp::Timestamp(v) => crate::wasi::filesystem::types::NewTimestamp::Timestamp(conv_e2i_datetime_22(v)),
    }
}
fn conv_e2i_advice_39(x: crate::exports::wasi::filesystem::types::Advice) -> crate::wasi::filesystem::types::Advice {
    match x {
        crate::exports::wasi::filesystem::types::Advice::Normal => crate::wasi::filesystem::types::Advice::Normal,
        crate::exports::wasi::filesystem::types::Advice::Sequential => crate::wasi::filesystem::types::Advice::Sequential,
        crate::exports::wasi::filesystem::types::Advice::Random => crate::wasi::filesystem::types::Advice::Random,
        crate::exports::wasi::filesystem::types::Advice::WillNeed => crate::wasi::filesystem::types::Advice::WillNeed,
        crate::exports::wasi::filesystem::types::Advice::DontNeed => crate::wasi::filesystem::types::Advice::DontNeed,
        crate::exports::wasi::filesystem::types::Advice::NoReuse => crate::wasi::filesystem::types::Advice::NoReuse,
    }
}
fn conv_e2i_ip_address_family_73(x: crate::exports::wasi::sockets::network::IpAddressFamily) -> crate::wasi::sockets::network::IpAddressFamily {
    match x {
        crate::exports::wasi::sockets::network::IpAddressFamily::Ipv4 => crate::wasi::sockets::network::IpAddressFamily::Ipv4,
        crate::exports::wasi::sockets::network::IpAddressFamily::Ipv6 => crate::wasi::sockets::network::IpAddressFamily::Ipv6,
    }
}
fn conv_e2i_ip_socket_address_79(x: crate::exports::wasi::sockets::network::IpSocketAddress) -> crate::wasi::sockets::network::IpSocketAddress {
    match x {
        crate::exports::wasi::sockets::network::IpSocketAddress::Ipv4(v) => crate::wasi::sockets::network::IpSocketAddress::Ipv4(conv_e2i_ipv4_socket_address_77(v)),
        crate::exports::wasi::sockets::network::IpSocketAddress::Ipv6(v) => crate::wasi::sockets::network::IpSocketAddress::Ipv6(conv_e2i_ipv6_socket_address_78(v)),
    }
}
fn conv_e2i_shutdown_type_100(x: crate::exports::wasi::sockets::tcp::ShutdownType) -> crate::wasi::sockets::tcp::ShutdownType {
    match x {
        crate::exports::wasi::sockets::tcp::ShutdownType::Receive => crate::wasi::sockets::tcp::ShutdownType::Receive,
        crate::exports::wasi::sockets::tcp::ShutdownType::Send => crate::wasi::sockets::tcp::ShutdownType::Send,
        crate::exports::wasi::sockets::tcp::ShutdownType::Both => crate::wasi::sockets::tcp::ShutdownType::Both,
    }
}
fn conv_e2i_outgoing_datagram_132(x: crate::exports::wasi::sockets::udp::OutgoingDatagram) -> crate::wasi::sockets::udp::OutgoingDatagram {
    crate::wasi::sockets::udp::OutgoingDatagram { data: x.data, remote_address: x.remote_address.map(|v| conv_e2i_ip_socket_address_79(v)) }
}
fn conv_i2e_stream_error_9(x: crate::wasi::io::streams::StreamError) -> crate::exports::wasi::io::streams::StreamError {
    match x {
        crate::wasi::io::streams::StreamError::LastOperationFailed(v) => crate::exports::wasi::io::streams::StreamError::LastOperationFailed(crate::exports::wasi::io::error::Error::new(PxError(v))),
        crate::wasi::io::streams::StreamError::Closed => crate::exports::wasi::io::streams::StreamError::Closed,
    }
}
fn conv_i2e_datetime_22(x: crate::wasi::clocks::wall_clock::Datetime) -> crate::exports::wasi::clocks::wall_clock::Datetime {
    crate::exports::wasi::clocks::wall_clock::Datetime { seconds: x.seconds, nanoseconds: x.nanoseconds }
}
fn conv_i2e_descriptor_type_29(x: crate::wasi::filesystem::types::DescriptorType) -> crate::exports::wasi::filesystem::types::DescriptorType {
    match x {
        crate::wasi::filesystem::types::DescriptorType::Unknown => crate::exports::wasi::filesystem::types::DescriptorType::Unknown,
        crate::wasi::filesystem::types::DescriptorType::BlockDevice => crate::exports::wasi::filesystem::types::DescriptorType::BlockDevice,
        crate::wasi::filesystem::types::DescriptorType::CharacterDevice => crate::exports::wasi::filesystem::types::DescriptorType::CharacterDevice,
        crate::wasi::filesystem::types::DescriptorType::Directory => crate::exports::wasi::filesystem::types::DescriptorType::Directory,
        crate::wasi::filesystem::types::DescriptorType::Fifo => crate::exports::wasi::filesystem::types::DescriptorType::Fifo,
        crate::wasi::filesystem::types::DescriptorType::SymbolicLink => crate::exports::wasi::filesystem::types::DescriptorType::SymbolicLink,
        crate::wasi::filesystem::types::DescriptorType::RegularFile => crate::exports::wasi::filesystem::types::DescriptorType::RegularFile,
        crate::wasi::filesystem::types::DescriptorType::Socket => crate::exports::wasi::filesystem::types::DescriptorType::Socket,
    }
}
fn conv_i2e_descriptor_flags_30(x: crate::wasi::filesystem::types::DescriptorFlags) -> crate::exports::wasi::filesystem::types::DescriptorFlags {
    crate::exports::wasi::filesystem::types::DescriptorFlags::from_bits_truncate(x.bits())
}
fn conv_i2e_descriptor_stat_35(x: crate::wasi::filesystem::types::DescriptorStat) -> crate::exports::wasi::filesystem::types::DescriptorStat {
    crate::exports::wasi::filesystem::types::DescriptorStat { type_: conv_i2e_descriptor_type_29(x.type_), link_count: x.link_count, size: x.size, data_access_timestamp: x.data_access_timestamp.map(|v| conv_i2e_datetime_22(v)), data_modification_timestamp: x.data_modification_timestamp.map(|v| conv_i2e_datetime_22(v)), status_change_timestamp: x.status_change_timestamp.map(|v| conv_i2e_datetime_22(v)) }
}
fn conv_i2e_directory_entry_37(x: crate::wasi::filesystem::types::DirectoryEntry) -> crate::exports::wasi::filesystem::types::DirectoryEntry {
    crate::exports::wasi::filesystem::types::DirectoryEntry { type_: conv_i2e_descriptor_type_29(x.type_), name: x.name }
}
fn conv_i2e_error_code_38(x: crate::wasi::filesystem::types::ErrorCode) -> crate::exports::wasi::filesystem::types::ErrorCode {
    match x {
        crate::wasi::filesystem::types::ErrorCode::Access => crate::exports::wasi::filesystem::types::ErrorCode::Access,
        crate::wasi::filesystem::types::ErrorCode::WouldBlock => crate::exports::wasi::filesystem::types::ErrorCode::WouldBlock,
        crate::wasi::filesystem::types::ErrorCode::Already => crate::exports::wasi::filesystem::types::ErrorCode::Already,
        crate::wasi::filesystem::types::ErrorCode::BadDescriptor => crate::exports::wasi::filesystem::types::ErrorCode::BadDescriptor,
        crate::wasi::filesystem::types::ErrorCode::Busy => crate::exports::wasi::filesystem::types::ErrorCode::Busy,
        crate::wasi::filesystem::types::ErrorCode::Deadlock => crate::exports::wasi::filesystem::types::ErrorCode::Deadlock,
        crate::wasi::filesystem::types::ErrorCode::Quota => crate::exports::wasi::filesystem::types::ErrorCode::Quota,
        crate::wasi::filesystem::types::ErrorCode::Exist => crate::exports::wasi::filesystem::types::ErrorCode::Exist,
        crate::wasi::filesystem::types::ErrorCode::FileTooLarge => crate::exports::wasi::filesystem::types::ErrorCode::FileTooLarge,
        crate::wasi::filesystem::types::ErrorCode::IllegalByteSequence => crate::exports::wasi::filesystem::types::ErrorCode::IllegalByteSequence,
        crate::wasi::filesystem::types::ErrorCode::InProgress => crate::exports::wasi::filesystem::types::ErrorCode::InProgress,
        crate::wasi::filesystem::types::ErrorCode::Interrupted => crate::exports::wasi::filesystem::types::ErrorCode::Interrupted,
        crate::wasi::filesystem::types::ErrorCode::Invalid => crate::exports::wasi::filesystem::types::ErrorCode::Invalid,
        crate::wasi::filesystem::types::ErrorCode::Io => crate::exports::wasi::filesystem::types::ErrorCode::Io,
        crate::wasi::filesystem::types::ErrorCode::IsDirectory => crate::exports::wasi::filesystem::types::ErrorCode::IsDirectory,
        crate::wasi::filesystem::types::ErrorCode::Loop => crate::exports::wasi::filesystem::types::ErrorCode::Loop,
        crate::wasi::filesystem::types::ErrorCode::TooManyLinks => crate::exports::wasi::filesystem::types::ErrorCode::TooManyLinks,
        crate::wasi::filesystem::types::ErrorCode::MessageSize => crate::exports::wasi::filesystem::types::ErrorCode::MessageSize,
        crate::wasi::filesystem::types::ErrorCode::NameTooLong => crate::exports::wasi::filesystem::types::ErrorCode::NameTooLong,
        crate::wasi::filesystem::types::ErrorCode::NoDevice => crate::exports::wasi::filesystem::types::ErrorCode::NoDevice,
        crate::wasi::filesystem::types::ErrorCode::NoEntry => crate::exports::wasi::filesystem::types::ErrorCode::NoEntry,
        crate::wasi::filesystem::types::ErrorCode::NoLock => crate::exports::wasi::filesystem::types::ErrorCode::NoLock,
        crate::wasi::filesystem::types::ErrorCode::InsufficientMemory => crate::exports::wasi::filesystem::types::ErrorCode::InsufficientMemory,
        crate::wasi::filesystem::types::ErrorCode::InsufficientSpace => crate::exports::wasi::filesystem::types::ErrorCode::InsufficientSpace,
        crate::wasi::filesystem::types::ErrorCode::NotDirectory => crate::exports::wasi::filesystem::types::ErrorCode::NotDirectory,
        crate::wasi::filesystem::types::ErrorCode::NotEmpty => crate::exports::wasi::filesystem::types::ErrorCode::NotEmpty,
        crate::wasi::filesystem::types::ErrorCode::NotRecoverable => crate::exports::wasi::filesystem::types::ErrorCode::NotRecoverable,
        crate::wasi::filesystem::types::ErrorCode::Unsupported => crate::exports::wasi::filesystem::types::ErrorCode::Unsupported,
        crate::wasi::filesystem::types::ErrorCode::NoTty => crate::exports::wasi::filesystem::types::ErrorCode::NoTty,
        crate::wasi::filesystem::types::ErrorCode::NoSuchDevice => crate::exports::wasi::filesystem::types::ErrorCode::NoSuchDevice,
        crate::wasi::filesystem::types::ErrorCode::Overflow => crate::exports::wasi::filesystem::types::ErrorCode::Overflow,
        crate::wasi::filesystem::types::ErrorCode::NotPermitted => crate::exports::wasi::filesystem::types::ErrorCode::NotPermitted,
        crate::wasi::filesystem::types::ErrorCode::Pipe => crate::exports::wasi::filesystem::types::ErrorCode::Pipe,
        crate::wasi::filesystem::types::ErrorCode::ReadOnly => crate::exports::wasi::filesystem::types::ErrorCode::ReadOnly,
        crate::wasi::filesystem::types::ErrorCode::InvalidSeek => crate::exports::wasi::filesystem::types::ErrorCode::InvalidSeek,
        crate::wasi::filesystem::types::ErrorCode::TextFileBusy => crate::exports::wasi::filesystem::types::ErrorCode::TextFileBusy,
        crate::wasi::filesystem::types::ErrorCode::CrossDevice => crate::exports::wasi::filesystem::types::ErrorCode::CrossDevice,
    }
}
fn conv_i2e_metadata_hash_value_40(x: crate::wasi::filesystem::types::MetadataHashValue) -> crate::exports::wasi::filesystem::types::MetadataHashValue {
    crate::exports::wasi::filesystem::types::MetadataHashValue { lower: x.lower, upper: x.upper }
}
fn conv_i2e_error_code_72(x: crate::wasi::sockets::network::ErrorCode) -> crate::exports::wasi::sockets::network::ErrorCode {
    match x {
        crate::wasi::sockets::network::ErrorCode::Unknown => crate::exports::wasi::sockets::network::ErrorCode::Unknown,
        crate::wasi::sockets::network::ErrorCode::AccessDenied => crate::exports::wasi::sockets::network::ErrorCode::AccessDenied,
        crate::wasi::sockets::network::ErrorCode::NotSupported => crate::exports::wasi::sockets::network::ErrorCode::NotSupported,
        crate::wasi::sockets::network::ErrorCode::InvalidArgument => crate::exports::wasi::sockets::network::ErrorCode::InvalidArgument,
        crate::wasi::sockets::network::ErrorCode::OutOfMemory => crate::exports::wasi::sockets::network::ErrorCode::OutOfMemory,
        crate::wasi::sockets::network::ErrorCode::Timeout => crate::exports::wasi::sockets::network::ErrorCode::Timeout,
        crate::wasi::sockets::network::ErrorCode::ConcurrencyConflict => crate::exports::wasi::sockets::network::ErrorCode::ConcurrencyConflict,
        crate::wasi::sockets::network::ErrorCode::NotInProgress => crate::exports::wasi::sockets::network::ErrorCode::NotInProgress,
        crate::wasi::sockets::network::ErrorCode::WouldBlock => crate::exports::wasi::sockets::network::ErrorCode::WouldBlock,
        crate::wasi::sockets::network::ErrorCode::InvalidState => crate::exports::wasi::sockets::network::ErrorCode::InvalidState,
        crate::wasi::sockets::network::ErrorCode::NewSocketLimit => crate::exports::wasi::sockets::network::ErrorCode::NewSocketLimit,
        crate::wasi::sockets::network::ErrorCode::AddressNotBindable => crate::exports::wasi::sockets::network::ErrorCode::AddressNotBindable,
        crate::wasi::sockets::network::ErrorCode::AddressInUse => crate::exports::wasi::sockets::network::ErrorCode::AddressInUse,
        crate::wasi::sockets::network::ErrorCode::RemoteUnreachable => crate::exports::wasi::sockets::network::ErrorCode::RemoteUnreachable,
        crate::wasi::sockets::network::ErrorCode::ConnectionRefused => crate::exports::wasi::sockets::network::ErrorCode::ConnectionRefused,
        crate::wasi::sockets::network::ErrorCode::ConnectionReset => crate::exports::wasi::sockets::network::ErrorCode::ConnectionReset,
        crate::wasi::sockets::network::ErrorCode::ConnectionAborted => crate::exports::wasi::sockets::network::ErrorCode::ConnectionAborted,
        crate::wasi::sockets::network::ErrorCode::DatagramTooLarge => crate::exports::wasi::sockets::network::ErrorCode::DatagramTooLarge,
        crate::wasi::sockets::network::ErrorCode::NameUnresolvable => crate::exports::wasi::sockets::network::ErrorCode::NameUnresolvable,
        crate::wasi::sockets::network::ErrorCode::TemporaryResolverFailure => crate::exports::wasi::sockets::network::ErrorCode::TemporaryResolverFailure,
        crate::wasi::sockets::network::ErrorCode::PermanentResolverFailure => crate::exports::wasi::sockets::network::ErrorCode::PermanentResolverFailure,
    }
}
fn conv_i2e_ip_address_family_73(x: crate::wasi::sockets::network::IpAddressFamily) -> crate::exports::wasi::sockets::network::IpAddressFamily {
    match x {
        crate::wasi::sockets::network::IpAddressFamily::Ipv4 => crate::exports::wasi::sockets::network::IpAddressFamily::Ipv4,
        crate::wasi::sockets::network::IpAddressFamily::Ipv6 => crate::exports::wasi::sockets::network::IpAddressFamily::Ipv6,
    }
}
fn conv_i2e_ip_address_76(x: crate::wasi::sockets::network::IpAddress) -> crate::exports::wasi::sockets::network::IpAddress {
    match x {
        crate::wasi::sockets::network::IpAddress::Ipv4(v) => crate::exports::wasi::sockets::network::IpAddress::Ipv4(v),
        crate::wasi::sockets::network::IpAddress::Ipv6(v) => crate::exports::wasi::sockets::network::IpAddress::Ipv6(v),
    }
}
fn conv_i2e_ip_socket_address_79(x: crate::wasi::sockets::network::IpSocketAddress) -> crate::exports::wasi::sockets::network::IpSocketAddress {
    match x {
        crate::wasi::sockets::network::IpSocketAddress::Ipv4(v) => crate::exports::wasi::sockets::network::IpSocketAddress::Ipv4(conv_i2e_ipv4_socket_address_77(v)),
        crate::wasi::sockets::network::IpSocketAddress::Ipv6(v) => crate::exports::wasi::sockets::network::IpSocketAddress::Ipv6(conv_i2e_ipv6_socket_address_78(v)),
    }
}
fn conv_i2e_incoming_datagram_130(x: crate::wasi::sockets::udp::IncomingDatagram) -> crate::exports::wasi::sockets::udp::IncomingDatagram {
    crate::exports::wasi::sockets::udp::IncomingDatagram { data: x.data, remote_address: conv_i2e_ip_socket_address_79(x.remote_address) }
}
fn conv_e2i_datetime_22(x: crate::exports::wasi::clocks::wall_clock::Datetime) -> crate::wasi::clocks::wall_clock::Datetime {
    crate::wasi::clocks::wall_clock::Datetime { seconds: x.seconds, nanoseconds: x.nanoseconds }
}
fn conv_e2i_ipv4_socket_address_77(x: crate::exports::wasi::sockets::network::Ipv4SocketAddress) -> crate::wasi::sockets::network::Ipv4SocketAddress {
    crate::wasi::sockets::network::Ipv4SocketAddress { port: x.port, address: x.address }
}
fn conv_e2i_ipv6_socket_address_78(x: crate::exports::wasi::sockets::network::Ipv6SocketAddress) -> crate::wasi::sockets::network::Ipv6SocketAddress {
    crate::wasi::sockets::network::Ipv6SocketAddress { port: x.port, flow_info: x.flow_info, address: x.address, scope_id: x.scope_id }
}
fn conv_i2e_ipv4_socket_address_77(x: crate::wasi::sockets::network::Ipv4SocketAddress) -> crate::exports::wasi::sockets::network::Ipv4SocketAddress {
    crate::exports::wasi::sockets::network::Ipv4SocketAddress { port: x.port, address: x.address }
}
fn conv_i2e_ipv6_socket_address_78(x: crate::wasi::sockets::network::Ipv6SocketAddress) -> crate::exports::wasi::sockets::network::Ipv6SocketAddress {
    crate::exports::wasi::sockets::network::Ipv6SocketAddress { port: x.port, flow_info: x.flow_info, address: x.address, scope_id: x.scope_id }
}

export!(Component);
