// The white-label step: everything app-specific lives in app.config.json, and
// this script projects it into the files the toolchain actually reads
// (capacitor.config.json, www/config.js). A different customer app is a
// different app.config.json, never an edit to the shell itself.
import { readFileSync, writeFileSync } from "node:fs";

const app = JSON.parse(readFileSync(new URL("./app.config.json", import.meta.url), "utf8"));

for (const key of ["name", "appId", "url", "repo"]) {
  if (!app[key]) throw new Error(`app.config.json is missing "${key}"`);
}
const origin = new URL(app.url).origin;
if (origin !== app.url.replace(/\/$/, "")) {
  throw new Error(`"url" must be a bare origin, got ${app.url}`);
}

const capacitor = {
  appId: app.appId,
  appName: app.displayName || app.name,
  webDir: "www",
  backgroundColor: app.backgroundColor || "#212121",
  server: {
    // The remote app stays INSIDE the webview; every other origin falls out
    // to the system browser. The repo pin and the verify flow assume this
    // list holds exactly the one app origin.
    allowNavigation: [new URL(app.url).host],
  },
};
writeFileSync(new URL("./capacitor.config.json", import.meta.url), JSON.stringify(capacitor, null, 2) + "\n");

// The splash reads its config as a module, so the bundle stays static and the
// webview never fetches configuration from anywhere it could be tampered with.
const cfg = {
  name: app.name,
  displayName: app.displayName || app.name,
  url: origin,
  attestationPath: app.attestationPath || "/attestation",
  repo: app.repo,
};
writeFileSync(
  new URL("./src/config.gen.js", import.meta.url),
  "// generated by configure.mjs from app.config.json - do not edit\n" +
    `export default ${JSON.stringify(cfg, null, 2)};\n`
);

console.log(`configured shell for ${cfg.displayName} (${app.appId} -> ${cfg.url}, repo pin ${cfg.repo})`);
