// The white-label seam: ONE shell, many apps. Everything app-specific lives
// in apps/<name>/app.json, and this script stamps it into every file the
// toolchain reads its identity from - the capacitor config, the splash
// config, and the native projects' name/id fields. The files it rewrites are
// committed with the eyesoff values; a CI matrix leg re-stamps them for its
// own app before building, so a different customer app is a directory with a
// json and an icon, never an edit to the shell.
//
//   node configure.mjs [app]     (or APP=<app>; default eyesoff)
import { readFileSync, writeFileSync } from "node:fs";

const APP = process.argv[2] || process.env.APP || "eyesoff";
const dir = new URL(`./apps/${APP}/`, import.meta.url);
const app = JSON.parse(readFileSync(new URL("app.json", dir), "utf8"));

for (const key of ["name", "displayName", "appId", "url", "repo", "icon"]) {
  if (!app[key]) throw new Error(`apps/${APP}/app.json is missing "${key}"`);
}
if (!/^[a-z][a-z0-9]*(\.[a-z][a-z0-9_]*)+$/i.test(app.appId)) {
  throw new Error(`"${app.appId}" is not a valid application id`);
}
const origin = new URL(app.url).origin;
if (origin !== app.url.replace(/\/$/, "")) {
  throw new Error(`"url" must be a bare origin, got ${app.url}`);
}
const bg = app.backgroundColor || "#212121";

// -- capacitor.config.json (generated, gitignored) ---------------------------
const capacitor = {
  appId: app.appId,
  appName: app.displayName,
  webDir: "www",
  backgroundColor: bg,
  server: {
    // The remote app stays INSIDE the webview; every other origin falls out
    // to the system browser. The repo pin and the verify flow assume this
    // list holds exactly the one app origin.
    allowNavigation: [new URL(app.url).host],
  },
};
writeFileSync(new URL("./capacitor.config.json", import.meta.url), JSON.stringify(capacitor, null, 2) + "\n");

// -- splash config (generated, gitignored; bundled into the local page) ------
// The icon rides along as a data: URI so the splash renders the brand with
// zero network - nothing the splash shows comes from anywhere tamperable.
const iconBytes = readFileSync(new URL(app.icon, dir));
const iconMime = /\.svg$/i.test(app.icon) ? "image/svg+xml" : "image/png";
const cfg = {
  name: app.name,
  displayName: app.displayName,
  url: origin,
  attestationPath: app.attestationPath || "/attestation",
  repo: app.repo,
  backgroundColor: bg,
  iconDataUri: `data:${iconMime};base64,${iconBytes.toString("base64")}`,
};
writeFileSync(
  new URL("./src/config.gen.js", import.meta.url),
  "// generated by configure.mjs from apps/" + APP + "/app.json - do not edit\n" +
    `export default ${JSON.stringify(cfg, null, 2)};\n`
);

// -- native identity (committed files, re-stamped in place) ------------------
const stamp = (rel, fn) => {
  const p = new URL(rel, import.meta.url);
  const before = readFileSync(p, "utf8");
  const after = fn(before);
  if (!after || after === before) return;
  writeFileSync(p, after);
};
const xml = (s) => String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

stamp("./android/app/build.gradle", (s) =>
  s.replace(/applicationId "[^"]+"/, `applicationId "${app.appId}"`));

stamp("./android/app/src/main/res/values/strings.xml", () =>
  `<?xml version='1.0' encoding='utf-8'?>\n<resources>\n` +
  `    <string name="app_name">${xml(app.displayName)}</string>\n` +
  `    <string name="title_activity_main">${xml(app.displayName)}</string>\n` +
  `    <string name="package_name">${app.appId}</string>\n` +
  `    <string name="custom_url_scheme">${app.appId}</string>\n` +
  `</resources>\n`);

stamp("./ios/App/App/Info.plist", (s) =>
  s.replace(/(<key>CFBundleDisplayName<\/key>\s*<string>)[^<]*(<\/string>)/, `$1${xml(app.displayName)}$2`));

stamp("./ios/App/App.xcodeproj/project.pbxproj", (s) =>
  s.replace(/PRODUCT_BUNDLE_IDENTIFIER = [^;]+;/g, `PRODUCT_BUNDLE_IDENTIFIER = ${app.appId};`));

console.log(`configured shell for ${app.displayName} (${app.appId} -> ${cfg.url}, repo pin ${cfg.repo})`);
