// risc-box patch (aot feature): bake profiled superblock regions into the
// interpreter as native code.
//
// Input: aot/regions.dump, written by a `--features tier2` boot-bench run
// (`--tier2 FILE`) driving the exact guest image the app will ship. Each
// region is the block set the runtime dispatcher formed, with the fnv-1a
// hash of its emit_region module — the key the runtime will look up, so a
// baked region only ever runs when the live guest's code bytes would have
// produced the very same module.
//
// Output: OUT_DIR/aot_regions.rs — one function per region, included into
// cpu.rs. Every op executes through Cpu::exec_op with a compile-time
// constant BlockOp, so the semantics are the interpreter's BY CONSTRUCTION
// (traps, MMIO, the SMC generation re-check after stores); what the bake
// removes is the per-op fetch/dispatch and the per-block probe, and what it
// adds is native control flow between the region's blocks.

use std::fmt::Write as _;
use std::path::Path;

#[derive(Clone, Copy)]
struct Op {
    imm: i32,
    word: u32,
    data: u16,
    kind: u8,
    rd: u8,
    rs1: u8,
    rs2: u8,
    len: u8,
}

fn main() {
    println!("cargo:rerun-if-changed=aot/regions.dump");
    let out = std::env::var("OUT_DIR").unwrap();
    let dst = Path::new(&out).join("aot_regions.rs");
    if std::env::var("CARGO_FEATURE_AOT").is_err() {
        // feature off: nothing includes the file, but write a stub so a
        // stale include never picks up old contents.
        std::fs::write(&dst, "// aot feature off\n").unwrap();
        return;
    }
    let dump = Path::new("aot/regions.dump");
    let regions = match std::fs::read_to_string(dump) {
        Ok(s) => parse(&s),
        Err(_) => Vec::new(),
    };
    let mut seen = std::collections::HashSet::new();
    let mut kept: Vec<(u64, Vec<(u64, Vec<Op>)>)> = Vec::new();
    for (h, blocks) in regions {
        if seen.insert(h) {
            kept.push((h, blocks));
        }
    }
    let mut s = String::new();
    let _ = writeln!(s, "// generated by build.rs from aot/regions.dump — do not edit");
    let _ = writeln!(s, "pub(crate) type AotFn = fn(&mut Cpu, u64, u32, u32) -> u64;");
    let mut hashes = String::new();
    let mut fns = String::new();
    for (i, (h, blocks)) in kept.iter().enumerate() {
        let _ = writeln!(hashes, "\t{:#018x},", h);
        let _ = writeln!(fns, "\taot_region_{},", i);
        emit_region_fn(&mut s, i, blocks);
    }
    let _ = writeln!(s, "pub(crate) static AOT_HASHES: &[u64] = &[\n{}];", hashes);
    let _ = writeln!(s, "pub(crate) static AOT_FNS: &[AotFn] = &[\n{}];", fns);
    std::fs::write(&dst, s).unwrap();
    println!(
        "cargo:warning=aot: baked {} regions from {}",
        kept.len(),
        dump.display()
    );
}

fn parse(s: &str) -> Vec<(u64, Vec<(u64, Vec<Op>)>)> {
    let mut out = Vec::new();
    let mut lines = s.lines().peekable();
    while let Some(line) = lines.next() {
        let mut w = line.split_whitespace();
        match w.next() {
            Some("REGION") => {
                let h = u64::from_str_radix(w.next().unwrap(), 16).unwrap();
                let n: usize = w.next().unwrap().parse().unwrap();
                let mut blocks = Vec::with_capacity(n);
                for _ in 0..n {
                    let bl = lines.next().unwrap();
                    let mut bw = bl.split_whitespace();
                    assert_eq!(bw.next(), Some("B"));
                    let pc = u64::from_str_radix(bw.next().unwrap(), 16).unwrap();
                    let cnt: usize = bw.next().unwrap().parse().unwrap();
                    let mut ops = Vec::with_capacity(cnt);
                    for _ in 0..cnt {
                        let ol = lines.next().unwrap();
                        let mut ow = ol.split_whitespace();
                        assert_eq!(ow.next(), Some("O"));
                        ops.push(Op {
                            imm: ow.next().unwrap().parse().unwrap(),
                            word: ow.next().unwrap().parse().unwrap(),
                            data: ow.next().unwrap().parse().unwrap(),
                            kind: ow.next().unwrap().parse().unwrap(),
                            rd: ow.next().unwrap().parse().unwrap(),
                            rs1: ow.next().unwrap().parse().unwrap(),
                            rs2: ow.next().unwrap().parse().unwrap(),
                            len: ow.next().unwrap().parse().unwrap(),
                        });
                    }
                    blocks.push((pc, ops));
                }
                out.push((h, blocks));
            }
            _ => {}
        }
    }
    out
}

/// Branch-family kinds — the only hot ops that can change pc (BEQ..BGEU 11-16,
/// JAL 19, JALR 20). Everything else keeps pc == next, so the taken-transfer
/// dispatch is emitted only where it can fire.
fn writes_pc(kind: u8) -> bool {
    (11..=16).contains(&kind) || kind == 19 || kind == 20
}

fn emit_region_fn(s: &mut String, idx: usize, blocks: &[(u64, Vec<Op>)]) {
    let member: Vec<u64> = blocks.iter().map(|&(pc, _)| pc).collect();
    let dispatch = |target_expr: &str| -> String {
        let mut d = String::new();
        let _ = writeln!(d, "\t\t\t\tmatch {} {{", target_expr);
        for (k, pc) in member.iter().enumerate() {
            let _ = writeln!(d, "\t\t\t\t\t{:#x}u64 => {{ t = {}; continue 'l; }}", pc, k);
        }
        let _ = writeln!(d, "\t\t\t\t\t_ => return retired,");
        let _ = writeln!(d, "\t\t\t\t}}");
        d
    };
    let _ = writeln!(s, "#[allow(unreachable_code, unreachable_patterns, unused_variables, unused_mut)]");
    let _ = writeln!(
        s,
        "fn aot_region_{}(cpu: &mut Cpu, fuel: u64, entry: u32, gen: u32) -> u64 {{",
        idx
    );
    let _ = writeln!(s, "\tlet mut retired: u64 = 0;");
    let _ = writeln!(s, "\tlet mut t: u32 = entry;");
    let _ = writeln!(s, "\t'l: loop {{");
    let _ = writeln!(s, "\t\tmatch t {{");
    for (k, (bpc, ops)) in blocks.iter().enumerate() {
        let _ = writeln!(s, "\t\t\t{} => {{ // block @ {:#x}", k, bpc);
        let _ = writeln!(s, "\t\t\t\tif retired >= fuel {{ return retired; }}");
        let mut pc = *bpc;
        let mut open = true;
        for op in ops {
            let addr = pc;
            let next = addr.wrapping_add(op.len as u64);
            pc = next;
            if op.kind == 0 {
                // the block's terminal non-hot op: it can change interrupt
                // or translation state, which must surface at the run loop.
                // Exit BEFORE it with pc exact; the interpreter runs it.
                let _ = writeln!(s, "\t\t\t\tcpu.pc = {:#x}u64;", addr);
                let _ = writeln!(s, "\t\t\t\treturn retired;");
                open = false;
                break;
            }
            let _ = writeln!(s, "\t\t\t\t{{");
            let _ = writeln!(
                s,
                "\t\t\t\t\tconst OP: BlockOp = BlockOp {{ imm: {}, word: {}, data: {}, kind: {}, rd: {}, rs1: {}, rs2: {}, len: {}, _pad: 0 }};",
                op.imm, op.word, op.data, op.kind, op.rd, op.rs1, op.rs2, op.len
            );
            let _ = writeln!(s, "\t\t\t\t\tcpu.pc = {:#x}u64;", next);
            let _ = writeln!(s, "\t\t\t\t\tlet r = cpu.exec_op(&OP, {:#x}u64);", addr);
            let _ = writeln!(s, "\t\t\t\t\tcpu.x[0] = 0;");
            let _ = writeln!(s, "\t\t\t\t\tretired += 1;");
            let _ = writeln!(
                s,
                "\t\t\t\t\tif let Err(e) = r {{ cpu.handle_exception(e, {:#x}u64); return retired; }}",
                addr
            );
            let _ = writeln!(s, "\t\t\t\t}}");
            if writes_pc(op.kind) {
                let _ = writeln!(s, "\t\t\t\tif cpu.pc != {:#x}u64 {{", next);
                let _ = write!(s, "{}", dispatch("cpu.pc"));
                let _ = writeln!(s, "\t\t\t\t}}");
            }
            // stores are kinds 1..=6 (HOT_STORE_MAX in cpu.rs): re-check the
            // write-snoop generation after each one, exactly as exec_block does
            if (1..=6).contains(&op.kind) {
                let _ = writeln!(
                    s,
                    "\t\t\t\tif cpu.mmu.code_gen() != gen {{ return retired; }}"
                );
            }
        }
        if open {
            // fallthrough off the block's end: pc == next of the last op
            let _ = write!(s, "{}", dispatch(&format!("{:#x}u64", pc)));
        }
        let _ = writeln!(s, "\t\t\t}}");
    }
    let _ = writeln!(s, "\t\t\t_ => return retired,");
    let _ = writeln!(s, "\t\t}}");
    let _ = writeln!(s, "\t}}");
    let _ = writeln!(s, "}}");
}
